### ISSUE TITLE
How to change filter parameters on the fly

### ISSUE THREAD

**Issue by AndreasSchmid1** [xtk93x/Leaflet.TileLayer.ColorFilter#2]
First, thank you for this great plugin. 

Is it possible to change the filter parameters on the fly with that plugin? I think about something described in this blogpost.

https://stackoverflow.com/a/49391668/690656

Thank you for help in advance

**Comment by xtk93x** [comment]
Hi, thank you so much for the feedback! 

I really like your idea! So I implemented a new function `updateFilter` to change the filter parameters on the fly. This new function can be used like this:
```js
myTileLayer.updateFilter(['grayscale:100%', 'invert:100%']);
```
Please, check out the [new demo](https://xtk93x.github.io/Leaflet.TileLayer.ColorFilter.updateFilter/) and the [demo code](https://github.com/xtk93x/xtk93x.github.io/tree/master/Leaflet.TileLayer.ColorFilter.updateFilter).

Don't forget to use the new version of the plugin. Feel free to contact me if you need more help.

Thank you for the awesome idea! :)

**Comment by AndreasSchmid1** [comment]
I have to thank you! That was blazing fast.

Tested it and works perfectly fine.
