### ISSUE TITLE
NPM package 

### ISSUE THREAD

**Issue by RignonNoel** [xtk93x/Leaflet.TileLayer.ColorFilter#3]
I really like this project and i would like to use it in some projects i maintain but i don't find a NPM package for it. Is it possible to put this beautiful project on NPM so we will be able to update it without copy/paste the base code in our repository ?

**Comment by xtk93x** [comment]
Thank you so much for the feedback! I will be working on it right now. This is one of my goals for today :).

**Comment by RignonNoel** [comment]
Oh nice! Look forward to integrating this plugin!

**Comment by xtk93x** [comment]
I think its ready! ([NPM](https://www.npmjs.com/package/leaflet.tilelayer.colorfilter))
```
npm install --save leaflet.tilelayer.colorfilter
```
Please, let me know if I am missing something.
Thanks!

**Comment by RignonNoel** [comment]
It's working for me!

Now i just need to find a way to plug this plugin with [ngx-leaflet](https://github.com/Asymmetrik/ngx-leaflet) to use it on Angular 6. Thanks :)

**Comment by xtk93x** [comment]
Great :)!

I tested with Angular 5 and the normal version of leaflet. For ngx-leaflet probably this guide may help: [Integrating Leaflet Plugins with ngx-leaflet](https://asymmetrik.com/ngx-leaflet-and-leaflet-plugins/). 

Leaflet.TileLayer.ColorFilter fits in the "Plugins that modify a global L variable" section.

> In this case, you have to import the whole Leaflet module into L. Then, you import the plugin library for side-effects. This is illustrated in the following snippet taken from the leaflet-path-transform example:

```
import { Component } from '@angular/core';

// Import Leaflet into L 
import * as L from 'leaflet';

// Import the plugin libraries so they will modify L
import 'leaflet.tilelayer.colorfilter';

@Component({
...
```

**Comment by RignonNoel** [comment]
After some research a really nice guy created me a full demo : https://github.com/kboul/ngx-color-filter

I don't know why but i can't just import colorFilter in the project, i need to put a reference to my `node_modules` folder. But it's working.

```

import * as L from 'leaflet';
import "../../../../../node_modules/leaflet.tilelayer.colorfilter/src/leaflet-tilelayer-colorfilter.js";

@Component({
  selector: 'app-home',
  templateUrl: './home-page.component.html',
  styleUrls: ['./home-page.component.scss'],
  encapsulation: ViewEncapsulation.None
})
export class HomePageComponent {

  map: L.Map;

  defaultToDarkFilter = [
    'grayscale: 80%'
  ];

  options = {
    layers: [
      (L.tileLayer as any).colorFilter('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        maxZoom: 18,
        attribution: '...' ,
        filter: this.defaultToDarkFilter
      }),
    ],
    zoom: 3,
    center: L.latLng(46.879966, -121.726909)
  };

```
